#!/usr/bin/env bash

export CONTECO_LABEL="module.ekg - ContEco"
export CONTECO_DESCRIPTION="An ElasticSearch based module with Kibana and Grafana."

export CONTECO_TYPE="module"
export CONTECO_NAME="ekg"
export CONTECO_TAG="7.1.1"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
